version: '3.8'

services:
  cuistudio-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuistudio-server
    ports:
      - "8000:8000"
    environment:
      # These will be loaded from .env file
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    volumes:
      # Mount temp directory for file processing
      - ./tmp:/tmp/recipe-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add a volume for persistent data
volumes:
  tmp-data:
